# Generated by Django 5.0.6 on 2024-07-01 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_pb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pb_data', models.CharField(max_length=500)),
                ('pb_status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read'), ('banned', 'Banned')], default='unread', max_length=500)),
                ('pb_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phobias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_TH', models.CharField(max_length=250)),
                ('name_ENG', models.CharField(max_length=250)),
                ('color', models.CharField(max_length=8)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
